### ISSUE TITLE
Pearson

### ISSUE THREAD

**Issue by davimeglioli** [FelixFrog/pdfgrabber#10]
dopo aver scaricato lo script nuovo continua a darmi lo stesso errore su pearson

**Comment by davimeglioli** [comment]
Ora su zanichelli, prima di visualizzare la lista dei libri questo: During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\david\Downloads\pdfgrabber-master (2)\pdfgrabber-master\main.py", line 222, in <module>
    main()
  File "C:\Users\david\Downloads\pdfgrabber-master (2)\pdfgrabber-master\main.py", line 204, in main
    downloadbook()
  File "C:\Users\david\Downloads\pdfgrabber-master (2)\pdfgrabber-master\main.py", line 107, in downloadbook
    coverpath = utils.cover(service, token, bid, book)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\Downloads\pdfgrabber-master (2)\pdfgrabber-master\utils.py", line 79, in cover
    open(coverpath, "wb").write(service.cover(token, bookid, data))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\Downloads\pdfgrabber-master (2)\pdfgrabber-master\services\znc.py", line 53, in cover
    r = requests.get("https://booktab-main-api.zanichelli.it/" + data["cover"].removesuffix(".png") + "@2x.png")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\requests\adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='booktab-main-api.zanichelli.it', port=443): Max retries exceeded with url: /coverz/9788808421975/9788808421975@2x.png (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000012795DE4110>, 'Connection to booktab-main-api.zanichelli.it timed out. (connect timeout=None)'))

**Comment by FelixFrog** [comment]
Ciao! Non riesco a riprodurre l'errore, e in effetti nell'ultimo aggiornamento non c'è stato nessun cambiamento che (almeno in teoria) possa aver influito su questo. Sembra che sia un problema di server zanichelli, ma se dici di avere lo stesso errore anche su pearson allora potrebbe essere un problema di requests su windows. Magari ritenta e fammi sapere se ti causa lo stesso errore.
