### ISSUE TITLE
sanoma

### ISSUE THREAD

**Issue by artifix100** [FelixFrog/pdfgrabber#109]
ciao scusa ho visto che altri hanno avuto stesso problema che il rendering non si completa a 98% . ho scaricato oggi ( su due macchine diverse ) ultima versione naturalmente ma errore è simile a quelli già visti 
Select a book or a comma-separated list of books: 11
Applying toc/labels ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺  98% 0:00:02
Traceback (most recent call last):
  File "C:\Users\Novelli\Downloads\github_com\pdfgrabber-master (3)\pdfgrabber-master\main.py", line 280, in <module>
    main()
  File "C:\Users\Novelli\Downloads\github_com\pdfgrabber-master (3)\pdfgrabber-master\main.py", line 261, in main
    downloadbook()
  File "C:\Users\Novelli\Downloads\github_com\pdfgrabber-master (3)\pdfgrabber-master\main.py", line 182, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Novelli\Downloads\github_com\pdfgrabber-master (3)\pdfgrabber-master\utils.py", line 53, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Novelli\Downloads\github_com\pdfgrabber-master (3)\pdfgrabber-master\services\snm.py", line 220, in downloadbook
    pdf.set_toc(toc)
  File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\fitz\utils.py", line 1330, in set_toc
    raise ValueError("row %i: page number out of range" % i)
ValueError: row 290: page number out of range
PS C:\Users\Novelli\Downloads\github_com\pdfgrabber-master (3)\pdfgrabber-master> 

ciao e grazie sempre

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
