### ISSUE TITLE
Pearson download

### ISSUE THREAD

**Issue by gabrySerra** [FelixFrog/pdfgrabber#15]
Quando accedo con il mio account e password, mi restituisce questi errori:

Traceback (most recent call last):
  File "C:\Users\Gabriele\Downloads\pdfgrabber-master\main.py", line 235, in <module>
    main()
  File "C:\Users\Gabriele\Downloads\pdfgrabber-master\main.py", line 217, in main
    downloadbook()
  File "C:\Users\Gabriele\Downloads\pdfgrabber-master\main.py", line 86, in downloadbook
    token = utils.login(service, username, password)
  File "C:\Users\Gabriele\Downloads\pdfgrabber-master\utils.py", line 29, in login
    service = getservice(servicename)
  File "C:\Users\Gabriele\Downloads\pdfgrabber-master\utils.py", line 25, in getservice
    service = importlib.import_module("services." + name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'services.prn'

Cosa posso fare?

**Comment by FelixFrog** [comment]
Ciao! Sei sicuro di aver scaricato tutta la cartella di pdfgrabber con tutti i suoi file? Sembrerebbe che te ne mancano alcuni. Altrimenti se a fianco di ```main.py``` c'è una cartella ```services``` con dentro un file ```prn.py``` dev'essere uno strano bug di windows.

**Comment by MattiaEffendi** [comment]
@FelixFrog questo problema è dato dal fatto che qualsiasi file con nome nel formato `prn.*` su windows non si può creare, infatti clonando il progetto (o scaricandolo come file .zip ed estraendolo), su windows il file viene rinominato in `_prn.py` e quindi non riesce a trovare il modulo.

Per risolvere ho modificato il nome del file in `prs.py` e cambiato la entry `prn` con `prs` alla riga 17 del file `services.py`. 

Così il tutto sembra funzionare!

**Comment by gabrySerra** [comment]
Ciao, non sono molto esperto, tuttavia ho scaricato due libri da bSmart senza problemi.
Se hai piacere posso mandarti qualche dettaglio più approfondito su Telegram.

**Comment by MattiaEffendi** [comment]
@gabrySerra prova a fare come ti descrivo ora:

- Nella cartella `services` trova il file con nome `prn.py` o simili, rinominalo in `prs.py`
- Nel file `utils.py`, alla riga 17, sostituisci "prn" con "prs"

A questo punto, ri-esegui il file main.py e dovrebbe andare tutto, ho avuto il tuo stesso problema oggi! :)

![image](https://user-images.githubusercontent.com/17389697/206927745-6d077147-7e9e-4b59-9ca1-94144335c67d.png)

**Comment by MattiaEffendi** [comment]
Non c'è problema, ci mancherebbe ahah
Ci sono rimasto un po'male anche io oggi quando ho notato questa roba, infatti avendo visto il file nella cartella services chiamato `_prn.py` mi sono reso conto di quale fosse il problema.

Fun fact: a quanto pare i file `prn` contengono i comandi dei driver delle stampanti che vengono utilizzati per creare un print job

**Comment by gabrySerra** [comment]
@MattiaEffendi Ora funziona perfettamente!
Grazie per l'aiuto :)
