### ISSUE TITLE
errore playwright Timeout 30000ms exceeded.

### ISSUE THREAD

**Issue by artifix100** [FelixFrog/pdfgrabber#18]
ciao sto usando grazie anche alle dritte di un amico questo tuo utilissimo script . ho riscontrato difficoltà per ora solo da zanichelli nel rendering in pdf dei libri  ti allego file log ; 

└────┴───────────────┴───────────────────────────────────────────────┘
Select a book or a comma-separated list of books: 7
Rendering page 43/46 ━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━  35% 0:05:39
Traceback (most recent call last):
  File "c:\Users\Novelli\Desktop\pdfgrabber\pdfgrabber-master\main.py", line 235, in <module>
    main()
  File "c:\Users\Novelli\Desktop\pdfgrabber\pdfgrabber-master\main.py", line 217, in main
    downloadbook()
  File "c:\Users\Novelli\Desktop\pdfgrabber\pdfgrabber-master\main.py", line 144, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Novelli\Desktop\pdfgrabber\pdfgrabber-master\utils.py", line 41, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Novelli\Desktop\pdfgrabber\pdfgrabber-master\services\znc.py", line 324, in downloadbook
    pdf, toc, labels = downloadkitaboo(token, bookid, pdf, toc, labels, progress, skipfirst)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Novelli\Desktop\pdfgrabber\pdfgrabber-master\services\znc.py", line 261, in downloadkitaboo
    bpage.goto(fullpath.as_uri())
  File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\sync_api\_generated.py", line 8200, in 
goto
    self._sync(
  File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_sync_base.py", line 104, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_page.py", line 491, in goto     
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_frame.py", line 147, in goto    
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 44, in send    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "file:///C:/Users/Novelli/AppData/Local/Temp/kitaboo.0n8o21r1/OPS/page0239.xhtml", waiting until "load"
============================================================
PS C:\Users\Novelli>

**Comment by FelixFrog** [comment]
Ciao! Sembra che ci sia un problema con il percorso del file che il browser non riesce a raggiungere. È un problema che si ripresenta più sempre oppure è successo soltanto una volta?

**Comment by artifix100** [comment]
Ciao grazie risposta si verifica sempre con due libri della lista in maniera random cioè non sempre alla stessa percentuale ma sempre nella,fase di rendering di un capitolo

**Comment by FelixFrog** [comment]
Mmmh... Sembrerebbe proprio un bug di playwright, o almeno della tua installazione. Prova a reinstallare playwright con ```pip install --force-reinstall playwright```

**Comment by artifix100** [comment]
Grazie ho provato il tuo suggerimento disinstallato e installato play wright,  ma niente continua quell'errore runtime.  Proverò su un sistema operativo magari più pulito in virtuale.  Comunque se hai altri consigli sono ben accetti

**Comment by artifix100** [comment]
Come ho detto ho provato in una installazione pulita su una partizione virtuale nuova di pacca,  e lo script ha funzionato correttamente,  portando a termine il rendering dei volumi kitaboo. Per cui ritengo se non risolto aggirato il problema :)

**Comment by FelixFrog** [comment]
Scusa mi ero perso l'aggiornamento! Direi che sembra proprio un bug di playwright, magari inierente ad un specifico sistema operativo/versione di chrome; in ogni caso sono contento che si sia risolto tutto.
