### ISSUE TITLE
Errore da Zanichelli

### ISSUE THREAD

**Issue by Tabiaso** [FelixFrog/pdfgrabber#22]
```
Traceback (most recent call last):dfgrabber-master\main.py", line 235, in <module>
  File "C:\Users\Tabià\Downloads\pdfgrabber-master\main.py", line 235, in <module>
    main()\Users\Tabià\Downloads\pdfgrabber-master\main.py", line 217, in main
  File "C:\Users\Tabià\Downloads\pdfgrabber-master\main.py", line 217, in main
    downloadbook()abià\Downloads\pdfgrabber-master\main.py", line 144, in downloadbook
  File "C:\Users\Tabià\Downloads\pdfgrabber-master\main.py", line 144, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)ok
  File "C:\Users\Tabià\Downloads\pdfgrabber-master\utils.py", line 41, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)nc.py", line 358, in downloadbook
  File "C:\Users\Tabià\Downloads\pdfgrabber-master\services\znc.py", line 358, in downloadbook
    pdf, toc, labels = downloadkitaboo(token, bookid, pdf, toc, labels, progress, skipfirst)taboo
  File "C:\Users\Tabià\Downloads\pdfgrabber-master\services\znc.py", line 257, in downloadkitaboo
    browser = p.chromium.launch()cal\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packag
  File "C:\Users\Tabià\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\sync_api\_generated.py", line 14083, in launch
    self._sync(s\Tabià\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packag
  File "C:\Users\Tabià\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_sync_base.py", line 104, in _sync
    return task.result()ppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packag
  File "C:\Users\Tabià\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))n.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packag
  File "C:\Users\Tabià\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(thonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packag
  File "C:\Users\Tabià\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()à\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packag
  File "C:\Users\Tabià\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()cutable doesn't exist at C:\Users\Tabià\AppData\Local\ms-playwright\chromium-1041\
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\Tabià\AppData\Local\ms-playwright\chromium-1041\chrome-win\chrome.exe════════════════════════════════════════╗
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
```

Ho rieseguito il comando pip install -r requirements.txt, e sono riuscito ad entrare, ma ora quando provo a scaricare un libro ho questo errore.

**Comment by Tabiaso** [comment]
Grazie della risposta. Quando provo ad eseguire il comando che mi hai detto, mi restituisce il seguente errore:

```
playwright : Termine 'playwright' non riconosciuto come nome di cmdlet, funzione, programma eseguibile o file script.
Controllare l'ortografia del nome o verificare che il percorso sia incluso e corretto, quindi riprovare.
In riga:1 car:1
+ playwright install
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (playwright:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
Forse è il mio computer che ha qualche anno sulle spalle?

**Comment by Bbalduzz** [comment]
forse non hai settato bene pip nel `PATH`. prova a eseguire `python -m playwright install`

**Comment by Tabiaso** [comment]
Ho eseguito il comando e ora funziona tutto alla perfezione, grazie per il supporto 👍
