### ISSUE TITLE
Error "page number out of range"

### ISSUE THREAD

**Issue by Tabiaso** [FelixFrog/pdfgrabber#23]
Ho scaricato un paio di libri da Scuolabook, ma quando provo a scaricare un determinato libro (storia), ottengo questo errore:

```
Traceback (most recent call last):
  File "C:\Users\Tabià\Downloads\pdfgrabber-master\main.py", line 235, in <module>
    main()
  File "C:\Users\Tabià\Downloads\pdfgrabber-master\main.py", line 217, in main
    downloadbook()
  File "C:\Users\Tabià\Downloads\pdfgrabber-master\main.py", line 144, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
  File "C:\Users\Tabià\Downloads\pdfgrabber-master\utils.py", line 41, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
  File "C:\Users\Tabià\Downloads\pdfgrabber-master\services\sbk.py", line 189, in downloadbook
    pdf.set_toc(toc)
  File "C:\Users\Tabià\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fitz\utils.py", line 1330, in set_toc
    raise ValueError("row %i: page number out of range" % i)
ValueError: row 4: page number out of range
```

**Comment by FelixFrog** [comment]
Ciao! Per sistemare questo errore contattami a @fflxx su telegram. Scuolabook è un po' rognoso ;-)

**Comment by Tabiaso** [comment]
Ti ho scritto, fammi sapere :)

**Comment by Tabiaso** [comment]
Problema risolto, Felix molto disponibile 💯
