### ISSUE TITLE
Pearson Token Error When trying to download

### ISSUE THREAD

**Issue by gettagly** [FelixFrog/pdfgrabber#25]
Choose a service [bsm/ees/hbs/mcm/myl/prs/sbk/znc/dbk/olb/rfl]: prs Do you have a token for Pearson eText / Reader+? [y/n] (n):

Traceback (most recent call last):
  File "/Users/j/Downloads/pdfgrabber-master/main.py", line 235, in <module>
    main()
  File "/Users/j/Downloads/pdfgrabber-master/main.py", line 217, in main
    downloadbook()
  File "/Users/j/Downloads/pdfgrabber-master/main.py", line 86, in downloadbook
    token = utils.login(service, username, password)
  File "/Users/j/Downloads/pdfgrabber-master/utils.py", line 30, in login
    token = service.login(username, password)
  File "/Users/j/Downloads/pdfgrabber-master/services/prs.py", line 187, in login
    rplususerinfo = getrplususerinfo(rplustoken["token"])
KeyError: 'token'

**Comment by FelixFrog** [comment]
Duplicato della issue #37, segno questa come completa. Segui lì la discussione.
