### ISSUE TITLE
raise ValueError("row %i: page number out of range" % i)

### ISSUE THREAD

**Issue by Esisxnem** [FelixFrog/pdfgrabber#27]
Ciao,
nello scaricaricare un libro da **Mondadori hub scuola** lo script ritorna il seguente codice di errore:

`Applying toc/labels ---------------------------------------   98% 0:00:01
Traceback (most recent call last):
  File "G:\Path\pdfgrabber\pdfgrabber-master\main.py", line 235, in <module>
    main()Avaliable services
  File "G:\Path\pdfgrabber\pdfgrabber-master\main.py", line 217, in main
    downloadbook()                    │
  File "G:\Path\pdfgrabber\pdfgrabber-master\main.py", line 144, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Path\pdfgrabber\pdfgrabber-master\utils.py", line 41, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Path\pdfgrabber\pdfgrabber-master\services\hbs.py", line 167, in downloadbook
    pdf = downloadbook_new(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Path\pdfgrabber\pdfgrabber-master\services\hbs.py", line 160, in downloadbook_new
    pdf.set_toc(toc)ner’s Bookshelf   │
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\fitz\utils.py", line 1330, in set_toc
    raise ValueError("row %i: page number out of range" % i)
ValueError: row 30: page number out of rangek/znc/dbk/olb/rfl]: hbs`

**NOTA**: Tutto OK con altri 4 libri

Cosa posso fare?

**Comment by RealRoti** [comment]
Ho lo stesso problema da MyLim. Con il primo libro tutto ok, il secondo da questo errore. Per caso hai trovato una soluzione?

**Comment by RealRoti** [comment]
Ciao, ho rilevato lo stesso identico problema con MyLim. Nello specifico il mio riporta
```
File "C:\Users\xxx\Downloads\pdfgrabber-master\main.py", line 271, in <module>
     main()
  File "C:\Users\xxxx\Downloads\pdfgrabber-master\main.py", line 253, in main
    downloadbook()ble services
  File "C:\Users\xxx\Downloads\pdfgrabber-master\main.py", line 174, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Downloads\pdfgrabber-master\utils.py", line 42, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Downloads\pdfgrabber-master\services\myl.py", line 87, in downloadbook
    pdf.set_toc(toc)                      │
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\fitz\utils.py", line 1333, in set_toc
    raise ValueError("row %i: page number out of range" % i)
ValueError: row 0: page number out of range
```
