### ISSUE TITLE
bSmart doesn't work. 

### ISSUE THREAD

**Issue by jacula** [FelixFrog/pdfgrabber#38]
With every bSmart download, I have:

``
Traceback (most recent call last):
  File "/home/jacula/Temp/pdfgrabber/main.py", line 235, in <module>
    main()

  File "/home/jacula/Temp/pdfgrabber/main.py", line 217, in main
    downloadbook()

  File "/home/jacula/Temp/pdfgrabber/main.py", line 144, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)

  File "/home/jacula/Temp/pdfgrabber/utils.py", line 41, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)

  File "/home/jacula/Temp/pdfgrabber/services/bsm.py", line 103, in downloadbook
    output, md5 = decryptfile(file)

  File "/home/jacula/Temp/pdfgrabber/services/bsm.py", line 51, in decryptfile
    dec = obj.decrypt(file.read(header[b"start"] - 256 - 16))
``

**Comment by jacula** [comment]
The problem is related with python version. It works, for example, with 3.10.6, but, for example, doesn't work with 3.10.9.
