### ISSUE TITLE
Libri Pearson errori

### ISSUE THREAD

**Issue by giapponesetimido** [FelixFrog/pdfgrabber#4]
Alcuni testi della Pearson non vengono scaricati generando un errore dopo il 20/30%. 
Questo è un esempio di codice che viene visualizzato:
Traceback (most recent call last):
  File "/Users/utente/Downloads/pdfgrabber-master/main.py", line 187, in <module>
    main()
  File "/Users/utente/Downloads/pdfgrabber-master/main.py", line 171, in main
    downloadbook()
  File "/Users/utente/Downloads/pdfgrabber-master/main.py", line 129, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
  File "/Users/utente/Downloads/pdfgrabber-master/utils.py", line 34, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
  File "/Users/utente/Downloads/pdfgrabber-master/services/prn.py", line 322, in downloadbook
    pdf = downloadrplusepub(data["url"], data["pwd"], progress)
  File "/Users/utente/Downloads/pdfgrabber-master/services/prn.py", line 294, in downloadrplusepub
    toc.extend(gentoc(tocitem.find("xhtml:ol", ns), 1, pages))
  File "/Users/utente/Downloads/pdfgrabber-master/services/prn.py", line 247, in gentoc
    toc.append([level, text, pages.index(href.split("#")[0]) + 1])
ValueError: 'https://link.pearson.it/216DBE8' is not in list

**Comment by giapponesetimido** [comment]
Intanto grazie mille per la disponibilità! Ho provato ma restituisce ancora un errore:
Grazie ancora!

Select a book or a comma-separated list of books: 25
Extracting epub ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━  31% -:--:--
Traceback (most recent call last):
  File "/Users/checco/Downloads/pdfgrabber-master/main.py", line 187, in <module>
    main()
  File "/Users/checco/Downloads/pdfgrabber-master/main.py", line 171, in main
    downloadbook()
  File "/Users/checco/Downloads/pdfgrabber-master/main.py", line 129, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
  File "/Users/checco/Downloads/pdfgrabber-master/utils.py", line 34, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
  File "/Users/checco/Downloads/pdfgrabber-master/services/prn.py", line 326, in downloadbook
    pdf = downloadrplusepub(data["url"], data["pwd"], progress)
  File "/Users/checco/Downloads/pdfgrabber-master/services/prn.py", line 296, in downloadrplusepub
    with webdriver.Chrome(options=chromeoptions, executable_path=lib.chromedriverlocation) as wd:
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: no chrome binary at /Users/fra/Downloads/Scuola/libri/pdfgrabber/renderer/Chromium.app/Contents/MacOS/Chromium
Stacktrace:
0   chromedriver                        0x000000010f8bf2c8 chromedriver + 4752072
1   chromedriver                        0x000000010f83f463 chromedriver + 4228195
2   chromedriver                        0x000000010f4a2b18 chromedriver + 441112
3   chromedriver                        0x000000010f4c7e29 chromedriver + 593449
4   chromedriver                        0x000000010f4c5e3c chromedriver + 585276
5   chromedriver                        0x000000010f508c43 chromedriver + 859203
6   chromedriver                        0x000000010f50874f chromedriver + 857935
7   chromedriver                        0x000000010f500b33 chromedriver + 826163
8   chromedriver                        0x000000010f4d19fd chromedriver + 633341
9   chromedriver                        0x000000010f4d3051 chromedriver + 639057
10  chromedriver                        0x000000010f88c30e chromedriver + 4543246
11  chromedriver                        0x000000010f890a88 chromedriver + 4561544
12  chromedriver                        0x000000010f8986df chromedriver + 4593375
13  chromedriver                        0x000000010f8918fa chromedriver + 4565242
14  chromedriver                        0x000000010f8672cf chromedriver + 4391631
15  chromedriver                        0x000000010f8b05b8 chromedriver + 4691384
16  chromedriver                        0x000000010f8b0739 chromedriver + 4691769
17  chromedriver                        0x000000010f8c681e chromedriver + 4782110
18  libsystem_pthread.dylib             0x00007ff815d394e1 _pthread_start + 125
19  libsystem_pthread.dylib             0x00007ff815d34f6b thread_start + 15

**Comment by giapponesetimido** [comment]
Con Hub Young non arrivo nemmeno all'elenco dei libri e restituisce il seguente errore:
Grazie!

Traceback (most recent call last):
  File "/Users/checco/Downloads/pdfgrabber-master/main.py", line 187, in <module>
    main()
  File "/Users/checco/Downloads/pdfgrabber-master/main.py", line 171, in main
    downloadbook()
  File "/Users/checco/Downloads/pdfgrabber-master/main.py", line 92, in downloadbook
    books = utils.library(service, token)
  File "/Users/checco/Downloads/pdfgrabber-master/utils.py", line 58, in library
    return service.library(token)
  File "/Users/checco/Downloads/pdfgrabber-master/services/hby.py", line 75, in library
    books[str(i["id"])] = {"title": i["title"] + " volume " + i["volume"], "cover": i["coverBig"]}
TypeError: can only concatenate str (not "NoneType") to str

**Comment by FelixFrog** [comment]
Ciao! Allora per il problema con i libri Pearson devi scaricarti una versione corrispondente di chromedriver e chromium/chrome. Poi nel file lib.py imposti le due path nelle righe 3 e 4 con il percorso dei due .exe. Per hubscuola è un fix facile, appena riesco lo sistemo

**Comment by giapponesetimido** [comment]
Ora Pearson funziona perfettamente! Grazie mille! Quando aggiornerai HubScuola ti farò sapere.

**Comment by giapponesetimido** [comment]
Se posso essere sfacciato, all'interno di Hub Scuola ci sono sia i libri per la Secondaria (https://young.hubscuola.it), per il quale hai configurato il file hby.py, ed i libri della Primaria (https://kids.hubscuola.it). È troppo complicato gestirli entrambi? Grazie mille per la disponibilità

**Comment by FelixFrog** [comment]
Ciao! 35f5a814c5d24370b9e9cb27340b3cf1dc260f96 dovrebbe sistemare il problema su Hub Young. Per quanto riguarda hub kids non ho idea, siccome non vi ho nessun libro. In teoria dovrebbe essere lo stesso sistema, e c'è una buona probabilità che funzioni comunque anche per quei libri nonostante lo script supporti esplicitamente solo Hub Young. In ogni caso prova con la versiona aggiornata dello script e fammi sapere.

**Comment by FelixFrog** [comment]
Se vuoi sono ben più che disponibile a darci un'occhiata, in teoria non dovrebbe essere troppo complicato. Se mi vuoi aiutare mi puoi contattare a @felixffx su twitter o @fflxx su telegram così ci spostiamo in privato.
