### ISSUE TITLE
bSmart error

### ISSUE THREAD

**Issue by edobett** [FelixFrog/pdfgrabber#40]
Traceback (most recent call last):────┘
  File "C:\Users\Edo\Desktop\Cuji\pdfgrabber-master\main.py", line 235, in <module>
    main()
  File "C:\Users\Edo\Desktop\Cuji\pdfgrabber-master\main.py", line 217, in main
    downloadbook()
  File "C:\Users\Edo\Desktop\Cuji\pdfgrabber-master\main.py", line 144, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edo\Desktop\Cuji\pdfgrabber-master\utils.py", line 41, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edo\Desktop\Cuji\pdfgrabber-master\services\bsm.py", line 103, in downloadbook
    output, md5 = decryptfile(file)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edo\Desktop\Cuji\pdfgrabber-master\services\bsm.py", line 47, in decryptfile
    header = msgpack.unpackb(file.read(256).rstrip(b"\x00"))
             ^^^^^^^
NameError: name 'msgpack' is not defined. Did you mean: 'umsgpack'?

**Comment by Bbalduzz** [comment]
ti consiglio di guardare questa issue:
https://github.com/FelixFrog/pdfgrabber/issues/39#issue-1752417405
