### ISSUE TITLE
Pearson Reader+: `StopIteration` at Extracting epub

### ISSUE THREAD

**Issue by BigB84** [FelixFrog/pdfgrabber#64]
Hi! 

Thanks so much for this tool!

I encouraged an error while downloading coursebook from Pearson Reader+

**Environment Info**
- OS: `ArchLinux`
- python: `3.11.6`
- run from venv with requirements installed by pip
- `MuPDF` and `chromium` installed from arch repo
- This happens in `d6e5631` commit latest at the time of writing issue (and at least one previous)

```shell
Select a book or a comma-separated list of books: 0
Extracting epub ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━  31% -:--:--
```
```python
Traceback (most recent call last):
  File "pdfgrabber/main.py", line 271, in <module>
    main()
  File "pdfgrabber/main.py", line 253, in main
    downloadbook()
  File "pdfgrabber/main.py", line 174, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pdfgrabber/utils.py", line 42, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pdfgrabber/services/prs.py", line 364, in downloadbook
    pdf = downloadrplusepub(data["url"], data["pwd"], progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pdfgrabber/services/prs.py", line 321, in downloadrplusepub
    tocitem = next(i for i in tocfile.find("xhtml:body", ns).findall("xhtml:nav", ns) if i.get("{http://www.idpf.org/2007/ops}type") == "toc")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

Could you help me plz?
How should I debug it?

**Comment by FelixFrog** [comment]
I pushed a temporary fix in 1a9c913
Let me know if it works, otherwise I will have to take a deeper dive

**Comment by BigB84** [comment]
Thanks for quick fix, I pulled changes but unfortunately still:

```python
Traceback (most recent call last):
  File "pdfgrabber/main.py", line 271, in <module>
    main()
  File "pdfgrabber/main.py", line 253, in main
    downloadbook()
  File "pdfgrabber/main.py", line 174, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pdfgrabber/utils.py", line 42, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pdfgrabber/services/prs.py", line 366, in downloadbook
    pdf = downloadrplusepub(data["url"], data["pwd"], progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pdfgrabber/services/prs.py", line 326, in downloadrplusepub
    pagelistitem = next(i for i in tocfile.find("xhtml:body", ns).findall("xhtml:nav", ns) if i.get("{http://www.idpf.org/2007/ops}type") == "page-list")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

**Comment by BigB84** [comment]
With `3f1c98c` also

```python
Traceback (most recent call last):
  File "pdfgrabber/main.py", line 271, in <module>
    main()
  File "pdfgrabber/main.py", line 253, in main
    downloadbook()
  File "pdfgrabber/main.py", line 174, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pdfgrabber/utils.py", line 42, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pdfgrabber/services/prs.py", line 431, in downloadbook
    pdf = downloadrplusepub(data["url"], data["pwd"], progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pdfgrabber/services/prs.py", line 391, in downloadrplusepub
    pagelistitem = next(i for i in tocfile.find("xhtml:body", ns).findall("xhtml:nav", ns) if i.get("{http://www.idpf.org/2007/ops}type") == "page-list")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

```

**Comment by FelixFrog** [comment]
You should contact me on [telegram](t.me/fflxx) as this looks like an error specific to this book.
