### ISSUE TITLE
ValueError: row 24: page number out of range while downloading from blk

### ISSUE THREAD

**Issue by mustafa-ad** [FelixFrog/pdfgrabber#73]
Hello, I got this error while downloading from Blinklearning.

Traceback (most recent call last):
  File "/home/user/Downloads/Compressed/pdfgrabber-master/main.py", line 271, in <module>
    main()
  File "/home/user/Downloads/Compressed/pdfgrabber-master/main.py", line 253, in main
    downloadbook()
  File "/home/user/Downloads/Compressed/pdfgrabber-master/main.py", line 174, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Downloads/Compressed/pdfgrabber-master/utils.py", line 42, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Downloads/Compressed/pdfgrabber-master/services/blk.py", line 20, in downloadbook
    return mcm.downloadbook(token, bookid, data, prorgess, blinklearning_baseurl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Downloads/Compressed/pdfgrabber-master/services/mcm.py", line 126, in downloadbook
    pdf.set_toc(toc)
  File "/home/user/Downloads/Compressed/pdfgrabber-master/.venv/lib/python3.12/site-packages/fitz/utils.py", line 1333, in set_toc
    raise ValueError("row %i: page number out of range" % i)
ValueError: row 24: page number out of range

**Comment by mustafa-ad** [comment]
Thank you for fixing that, now I receive this with some books:

Traceback (most recent call last):
  File "/home/user/Downloads/Compressed/pdfgrabber-master/main.py", line 271, in <module>
    main()
  File "/home/user/Downloads/Compressed/pdfgrabber-master/main.py", line 253, in main
    downloadbook()
  File "/home/user/Downloads/Compressed/pdfgrabber-master/main.py", line 174, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Downloads/Compressed/pdfgrabber-master/utils.py", line 42, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Downloads/Compressed/pdfgrabber-master/services/blk.py", line 20, in downloadbook
    return mcm.downloadbook(token, bookid, data, prorgess, blinklearning_baseurl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Downloads/Compressed/pdfgrabber-master/services/mcm.py", line 128, in downloadbook
    supdf = fitz.Document(stream=files[filename], filetype="pdf")
                                 ~~~~~^^^^^^^^^^
KeyError: '"****There is a key here I thought it is better to hide it"****.pdf'
