### ISSUE TITLE
Hub Scuola error: no objects found

### ISSUE THREAD

**Issue by rictech** [FelixFrog/pdfgrabber#79]
Quando provo a scaricare un libro su hub scuola mi restituisce il seguente errore:
Traceback (most recent call last):
  File "C:\Disco_D\000D Documenti\APPOGGIO PROGRAMMI\PDFGrabber_Launcher-main\main.py", line 271, in <module>
    main()
  File "C:\Disco_D\000D Documenti\APPOGGIO PROGRAMMI\PDFGrabber_Launcher-main\main.py", line 253, in main
    downloadbook()
  File "C:\Disco_D\000D Documenti\APPOGGIO PROGRAMMI\PDFGrabber_Launcher-main\main.py", line 174, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Disco_D\000D Documenti\APPOGGIO PROGRAMMI\PDFGrabber_Launcher-main\utils.py", line 42, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Disco_D\000D Documenti\APPOGGIO PROGRAMMI\PDFGrabber_Launcher-main\services\hbs.py", line 167, in downloadbook
    pdf = downloadbook_new(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Disco_D\000D Documenti\APPOGGIO PROGRAMMI\PDFGrabber_Launcher-main\services\hbs.py", line 136, in downloadbook_new
    pdf = fitz.Document(stream=pdfbytes, filetype="pdf")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alema\AppData\Local\Programs\Python\Python312\Lib\site-packages\fitz\__init__.py", line 2733, in __init__
    doc = mupdf.fz_open_document_with_stream(magic, data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alema\AppData\Local\Programs\Python\Python312\Lib\site-packages\fitz\mupdf.py", line 44057, in fz_open_document_with_stream
    return _mupdf.fz_open_document_with_stream(magic, stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fitz.mupdf.FzErrorFormat: code=7: no objects found

**Comment by sangkavr** [comment]
Stesso problema. C'è soluzione?

**Comment by emcpteam** [comment]
Stesso problema.
