### ISSUE TITLE
libri pearson

### ISSUE THREAD

**Issue by davimeglioli** [FelixFrog/pdfgrabber#8]
Dopo aver eseguito main.py, fatto accesso, scelto libri pearson, immesso le credenziali di Pearson, ricevo questo errore

Traceback (most recent call last):
  File "C:\Users\david\Downloads\pdfgrabber-master (1)\rebuilt.pdfgrabber-master (1)\pdfgrabber-master\main.py", line 194, in <module>
    main()
  File "C:\Users\david\Downloads\pdfgrabber-master (1)\rebuilt.pdfgrabber-master (1)\pdfgrabber-master\main.py", line 178, in main
    downloadbook()
  File "C:\Users\david\Downloads\pdfgrabber-master (1)\rebuilt.pdfgrabber-master (1)\pdfgrabber-master\main.py", line 78, in downloadbook
    token = utils.login(service, username, password)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\Downloads\pdfgrabber-master (1)\rebuilt.pdfgrabber-master (1)\pdfgrabber-master\utils.py", line 20, in login
    service = getservice(servicename)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\Downloads\pdfgrabber-master (1)\rebuilt.pdfgrabber-master (1)\pdfgrabber-master\utils.py", line 16, in getservice
    service = importlib.import_module("services." + name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'services.prn'

Come risolvo? Non sono molto esperto

**Comment by aleeessio** [comment]
Penso ti manchi il modulo necessario.

**Comment by davimeglioli** [comment]
fatto ma continua a restituire lo stesso errore

**Comment by davimeglioli** [comment]
tutto questo accade prima di visualizzare l'elenco dei libri

**Comment by aleeessio** [comment]
> tutto questo accade prima di visualizzare l'elenco dei libri

Ma tu stai cercando di scaricare una lista di libri? Nel caso prova a scaricarli singolarmente

**Comment by davimeglioli** [comment]
No, singolarmente, ma non riesco neanche a visualizzare la lista. Viene visualizzato subito dopo aver inserito le credenziali di pearson

**Comment by aleeessio** [comment]
> No, singolarmente, ma non riesco neanche a visualizzare la lista. Viene visualizzato subito dopo aver inserito le credenziali di pearson
> 

Ok si effettivamente c'è un errore che parte dal token, lo da anche a me

**Comment by davimeglioli** [comment]
Inoltre, per scaricare quelli di zanichelli, in alcuni, dopo aver fatto partire il download restituisce questo

te lo scrivo direttamente qui, cosi se devi riguardare lo script riguardi anche questo

Traceback (most recent call last):    
  File "C:\Users\david\Downloads\pdfgrabber-master (1)\rebuilt.pdfgrabber-master (1)\pdfgrabber-master\main.py", line 194, in <module>
    main()EE2                        
  File "C:\Users\david\Downloads\pdfgrabber-master (1)\rebuilt.pdfgrabber-master (1)\pdfgrabber-master\main.py", line 178, in main
    downloadbook()k                 
  File "C:\Users\david\Downloads\pdfgrabber-master (1)\rebuilt.pdfgrabber-master (1)\pdfgrabber-master\main.py", line 134, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\Downloads\pdfgrabber-master (1)\rebuilt.pdfgrabber-master (1)\pdfgrabber-master\utils.py", line 34, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\Downloads\pdfgrabber-master (1)\rebuilt.pdfgrabber-master (1)\pdfgrabber-master\services\znc.py", line 308, in downloadbook
    pdf, toc, labels = downloadkitaboo(token, bookid, pdf, toc, labels, progress)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\Downloads\pdfgrabber-master (1)\rebuilt.pdfgrabber-master (1)\pdfgrabber-master\services\znc.py", line 246, in downloadkitaboo
    sizematch = re.search('content.+?width\s{,1}=\s{,1}([0-9]+).+?height\s{,1}=\s{,1}([0-9]+)', open(fullpath).read())
                                                                                                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 831: character maps to <undefined>

**Comment by FelixFrog** [comment]
Ciao! per il primo errore è semplicemente una questione di eseguire ```python main.py``` dalla directory in cui è contenuto il file. Questa per ora è una limitazione totalmente aribtraria, fra non tanto dovrei pubblicare il fix. Mentre il secondo errore è semplicaemente una questione di encoding dei file su windows, per quello mi basta aggiungere una dozzina di caratteri

**Comment by FelixFrog** [comment]
Entrambi i bug sono sistemati con 0b4cb3c430b22480d899412be6153cfefcddb06f. Fatemi sapere se ci sono problemi.
