### ISSUE TITLE
Keyerror in blk

### ISSUE THREAD

**Issue by TheUnrealZaka** [FelixFrog/pdfgrabber#81]
Traceback (most recent call last):
  File "/home/theunrealzaka/pdfgrabber/main.py", line 271, in <module>
    main()
  File "/home/theunrealzaka/pdfgrabber/main.py", line 253, in main
    downloadbook()
  File "/home/theunrealzaka/pdfgrabber/main.py", line 119, in downloadbook
    books = utils.library(service, token)
  File "/home/theunrealzaka/pdfgrabber/utils.py", line 99, in library
    return service.library(token)
  File "/home/theunrealzaka/pdfgrabber/services/blk.py", line 17, in library
    return mcm.library(token, blinklearning_baseurl)
  File "/home/theunrealzaka/pdfgrabber/services/mcm.py", line 89, in library
    coursejson = json.load(userzip.open("coursePlayer/curso_json_idcurso_" + cid + ".htm"))
  File "/home/theunrealzaka/.pyenv/versions/3.10.7/lib/python3.10/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/home/theunrealzaka/.pyenv/versions/3.10.7/lib/python3.10/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: "There is no item named 'coursePlayer/curso_json_idcurso_3805042.htm' in the archive"

**Comment by TheUnrealZaka** [comment]
Fixed itself the error
![image](https://github.com/FelixFrog/pdfgrabber/assets/59831000/66883c66-aa07-4fab-a39f-a24bed1a6883)
