### ISSUE TITLE
Blinklearning download error

### ISSUE THREAD

**Issue by helenup66** [FelixFrog/pdfgrabber#82]
Good evening. When I try to download book from Blinklearning, I have this error. It was happend yesterday. Before yesterday i have downloaded all books I bought 
![2024-04-20_19-18-55](https://github.com/FelixFrog/pdfgrabber/assets/151519267/e66ec77c-0c31-4616-846d-e7b6e1f0a8a7)

**Comment by TheUnrealZaka** [comment]
Yea, sometimes happens with BlinkLearning. You need to wait 4 hours and it will fix itself.

**Comment by markos00** [comment]
Hi! I'm having the same problem unfortunately. Has BlinkLearning changed its api in the meantime?
`Traceback (most recent call last):
  File "C:\Users\--\Desktop\pdfgrabber-master\main.py", line 271, in <module>
    main()
  File "C:\Users\--\Desktop\pdfgrabber-master\main.py", line 253, in main
    downloadbook()
  File "C:\Users\--\Desktop\pdfgrabber-master\main.py", line 119, in downloadbook
    books = utils.library(service, token)
  File "C:\Users\--\Desktop\pdfgrabber-master\utils.py", line 99, in library
    return service.library(token)
  File "C:\Users\--\Desktop\pdfgrabber-master\services\blk.py", line 17, in library
    return mcm.library(token, blinklearning_baseurl)
  File "C:\Users\--\Desktop\pdfgrabber-master\services\mcm.py", line 89, in library
    coursejson = json.load(userzip.open("coursePlayer/curso_json_idcurso_" + cid + ".htm"))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1516, in open
    zinfo = self.getinfo(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1443, in getinfo
    raise KeyError(
KeyError: "There is no item named 'coursePlayer/curso_json_idcurso_4427866.htm' in the archive"`
