### ISSUE TITLE
CNG KeyError: 'logicalPageNumber'

### ISSUE THREAD

**Issue by phantanvietpk** [FelixFrog/pdfgrabber#84]
Hi!

Thanks so much for this tool!

I encouraged an error while downloading coursebook from Cengage Read

```
Extracting zip ━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━  46% 0:00:12
Traceback (most recent call last):
  File "/Users/Downloads/pdfgrabber/main.py", line 271, in <module>
    main()
  File "/Users/Downloads/pdfgrabber/main.py", line 253, in main
    downloadbook()
  File "/Users/Downloads/pdfgrabber/main.py", line 174, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Downloads/pdfgrabber/utils.py", line 42, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Downloads/pdfgrabber/services/cng.py", line 246, in downloadbook
    pdf = downloadhtml5(accesstoken, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Downloads/pdfgrabber/services/cng.py", line 214, in downloadhtml5
    totpages, toc, totnum = linearize(structure["book"], 1, 1)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/des/Downloads/pdfgrabber/services/cng.py", line 190, in linearize
    if i["title"] != i["logicalPageNumber"]:
                     ~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'logicalPageNumber'

```

**Comment by pitcany** [comment]
Same here.

**Comment by gostovimr** [comment]
Encountered This Issue Does Anybody Know a Work Around
